# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.TimeField()),
                ('getter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getter', to='users.Users')),
                ('setter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setter', to='users.Users')),
            ],
        ),
    ]
