# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20161020_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='getter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getter', to='users.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='setter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setter', to='users.User'),
        ),
    ]
