# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20161029_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='date',
        ),
    ]
