# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20161107_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
