# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='claz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('proffession', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='sender',
            field=models.ForeignKey(on_delete='id', to='users.Users'),
        ),
        migrations.AddField(
            model_name='test',
            name='testclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.claz'),
        ),
        migrations.AddField(
            model_name='claz',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil', to='users.Users'),
        ),
        migrations.AddField(
            model_name='claz',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='users.Users'),
        ),
    ]
