# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161017_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='send',
        ),
    ]
