# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_test_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='send',
            field=models.ForeignKey(default=1.9, on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
            preserve_default=False,
        ),
    ]
