# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_test_send'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='send',
            new_name='sender',
        ),
    ]
