# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161017_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claz',
            name='pupil',
        ),
        migrations.RemoveField(
            model_name='claz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='test',
            name='testclass',
        ),
        migrations.DeleteModel(
            name='claz',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
