# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_clasz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clasz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Classes'),
        ),
    ]
