# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20161018_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='pupils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil', to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('mark', models.IntegerField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
                ('testclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
        ),
    ]
