# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161018_1234'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupils',
            name='clas',
        ),
        migrations.RemoveField(
            model_name='pupils',
            name='pupil',
        ),
        migrations.AddField(
            model_name='classes',
            name='pupils',
            field=models.ManyToManyField(to='users.Users'),
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='tests'),
        ),
        migrations.DeleteModel(
            name='pupils',
        ),
    ]
