# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20161020_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='classname',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
